package iotap.host.host.AppFiles.controllers;

import iotap.host.host.AppFiles.entities.Task;
import iotap.host.host.AppFiles.repositories.TaskDetailRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/task") // This means URL's start with /demo (after Application path)
public class TaskController {
    @Qualifier("taskDetailRepository")
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private TaskDetailRepository taskDetailRepository;

    @GetMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody String addNewTask (@RequestParam String location
            , @RequestParam String name, @RequestParam String description) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Task n = new Task(name, location, description, null, null, false, false, 5);
        taskDetailRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Task> getAllTaskDetails() {
        // This returns a JSON or XML with the users
        return taskDetailRepository.findAll();
    }
}
